# This is a basic workflow to help you get started with Actions

name: Build & Deploy to Docker hub

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Build and Deploy on Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: isbkch/ip-geolocator-swoole
        tags: latest
